apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kitchensink
spec:
  replicas: 2
  selector:
    name: kitchensink
  template:
    metadata:
      labels:
        name: kitchensink
    spec:
      containers:
      - name: kitchensink
        image: kitchensink:1.0-prod
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
          name: jolokia
  strategy:
    type: Recreate
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - kitchensink
      from:
        kind: ImageStreamTag
        name: kitchensink:1.0-prod
        namespace: kitchensink-dev
  - type: ConfigChange

