apiVersion: v1
kind: BuildConfig
metadata:
  name: kitchensink
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ulx-demo/kitchensink
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap64-openshift:latest
        namespace: openshift
      env:
      - name: "ARTIFACT_DIR"
        value: "ear/target/"

  output:
    to:
      kind: ImageStreamTag
      name: kitchensink:latest

